import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Banner from '../components/Banner'
import SmallCard from '../components/SmallCard'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <Header />
       <Banner />

       <p className='mt-8 text-white font-semibold text-4xl'>Explore Nearby</p>

      <SmallCard />
      
    </div>
  )
}
